### ISSUE TITLE
Kenel Always Shut Down When Using VScode jupyter plugins to run .ipynb files on GPU Farm

### ISSUE THREAD

**Issue by Yang-Jiajian** [VIOLINARTHUR/HKU-DASC7606-A1#3]
I use SSH to connect my GPU Farm Server and I have installed jupyer ipykernel in remote environment. I choose my conda environment as kernel, but it always shut down.
![image](https://github.com/user-attachments/assets/28b5a4a5-984e-4bc8-ad87-a96a9fc352dc)

**Comment by TianshuoY** [comment]
Please follow the five-step tutorial for using GPU Farm. The issue here arises from not configuring the step 5. So your jupyter notebook is not running on the GPU compute node.
Link here: [Running Jupyter Lab without Starting a Web Browser](https://www.cs.hku.hk/gpu-farm/quickstart#:~:text=Running%20Jupyter%20Lab%20without%20Starting%20a%20Web%20Browser)
